version: "2"

linters:
  enable:
    - gofmt
    - goimports
    - stylecheck
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - varnamelen
    - revive

  revive:
    # Recommended settings as in https://github.com/mgechev/revive#recommended-configuration
    ignore-generated-header: false
    severity: warning
    confidence: 0.6
    error-code: 0
    warning-code: 0

    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  varnamelen:
    min-name-length: 2
    ignore-names:
    - r
    - w
    - a
    - u
    - i
    - s
    - t
    - v
